export const seedRoutes = [
  {
    id: "R-1001",
    routeNo: "R-1001",
    depotCode: "RMS",
    vehicleId: "VH-001",
    driverId: "DRV-001",
    status: "Draft",
    plannedDate: new Date().toISOString().slice(0, 10),
    plannedKm: 118,
    plannedMinutes: 410,
    totalCases: 920,
    totalWeightKg: 7400,
    totalCbm: 21.5,
    totalEf: 88,
    estimatedCost: 146,
  },
  {
    id: "R-1002",
    routeNo: "R-1002",
    depotCode: "RMS",
    vehicleId: "VH-002",
    driverId: "DRV-002",
    status: "Released",
    plannedDate: new Date().toISOString().slice(0, 10),
    plannedKm: 96,
    plannedMinutes: 360,
    totalCases: 760,
    totalWeightKg: 6100,
    totalCbm: 18.2,
    totalEf: 74,
    estimatedCost: 123,
  },
];

export const seedOrders = [
  {
    id: "ORD-501",
    customerCode: "CUS-1001",
    customerName: "Al Noor Hypermarket",
    depotCode: "RMS",
    cases: 120,
    weightKg: 960,
    cbm: 2.8,
    status: "Unassigned",
    routeId: null,
    stopId: null,
  },
  {
    id: "ORD-502",
    customerCode: "CUS-1002",
    customerName: "Muscat Mart",
    depotCode: "RMS",
    cases: 80,
    weightKg: 640,
    cbm: 1.9,
    status: "Assigned",
    routeId: "R-1001",
    stopId: "STOP-1",
  },
];

export const seedTelemetry = [
  {
    id: "gps-seed-001",
    driverId: "DRV-001",
    vehicleId: "VH-001",
    routeId: "R-1001",
    latitude: 23.5880,
    longitude: 58.3829,
    speedKph: 42,
    heading: 95,
    capturedAt: new Date().toISOString(),
    receivedAt: new Date().toISOString(),
  },
];
